# GitHub Pages configuration
theme: jekyll-theme-minimal
title: "Stable Marriage Problem Demo"
description: "Interactive Gale-Shapley Algorithm Visualization"

# Enable plugins
plugins:
  - jekyll-relative-links

# Relative links settings
relative_links:
  enabled: true
  collections: true

# Exclude files from build
exclude:
  - README.md
  - .github/